### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by ablito19** [Athena-OS/athena#101]
Hello
I have only One option for installation, and it is Online Installation. When i run it, i got black screen, nothing else.

And i can't see offline option.

Support pls

**Comment by D3vil0p3r** [comment]
It occurs before or after system installation? Which environment did you choose? Are u in VM or baremetal?

**Comment by ablito19** [comment]
I boot it from USB for make fresh installation. When i click Online Installation, nothing work

**Comment by zennvoan12** [comment]
i mean like this blank but i have found bug for nvidia user

**Comment by zennvoan12** [comment]
![WhatsApp Image 2024-01-04 at 21 25 06_a991fa1e](https://github.com/Athena-OS/athena-iso/assets/72489361/6dea84bc-e237-43fb-a909-207334be1e62)
![WhatsApp Image 2024-01-04 at 21 25 06_200f9f2a](https://github.com/Athena-OS/athena-iso/assets/72489361/ee4fc312-ded2-4c4c-ba5a-be8fca98219e)
![WhatsApp Image 2024-01-04 at 21 25 06_a991fa1e](https://github.com/Athena-OS/athena-iso/assets/72489361/7a371173-43ec-4363-a963-a56974e67f13)

**Comment by D3vil0p3r** [comment]
Try to wait, it needs time.

**Comment by zennvoan12** [comment]
yeah i'm waiting 3 hour. fair enough i was

**Comment by D3vil0p3r** [comment]
It is clearly an issue but I need more info

**Comment by zennvoan12** [comment]
my case, i think. used nvidia nouvaeu. i meant why not supported . i know my tech was so old nvidia 920mx but why ??

**Comment by zennvoan12** [comment]
![WhatsApp Image 2024-01-05 at 23 25 52_cb647982](https://github.com/Athena-OS/athena-iso/assets/72489361/fe6ae15a-f9fd-444c-a3da-8dd3a9639d2a)


what's next

**Comment by D3vil0p3r** [comment]
I uploaded a new ISO where I removed BA. Download it and try.

**Comment by D3vil0p3r** [comment]
The latest ISO is working well? https://github.com/Athena-OS/athena/releases/tag/v23.11 Did you solve your issue?
