### ISSUE TITLE
[BUG]:  blackarch signature

### ISSUE THREAD

**Issue by zennvoan12** [Athena-OS/athena#102]
### Athena OS version

Athna OS athena-rolling-x86_64

### Which environment or technology are you using?

- [X] Baremetal
- [ ] VirtualBox Virtual Machine
- [ ] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Kernel version

6.2.11-lts-1-lts

### Repro steps

![WhatsApp Image 2024-01-06 at 08 32 28_ec047f68](https://github.com/Athena-OS/athena-iso/assets/72489361/cda431f1-cb74-4d5d-addf-3ad5f278d280)

### Expected behavior

![image](https://github.com/Athena-OS/athena-iso/assets/72489361/223a6daf-caa0-4efe-8416-4314df12308d)

### Actual behavior

![image](https://github.com/Athena-OS/athena-iso/assets/72489361/8d10c064-6387-4895-bea7-3307dc0c6d66)

**Comment by zennvoan12** [comment]
before i was updated mirror on blackarch official but nothing happened. can i have solution

**Comment by D3vil0p3r** [comment]
I uploaded a new ISO where I removed BA. Download it and try.

**Comment by D3vil0p3r** [comment]
> before i was updated mirror on blackarch official but nothing happened. can i have solution

Get it by https://github.com/Athena-OS/athena/releases/tag/v23.11 and let me know.
