### ISSUE TITLE
[BUG]: issue installing on HP SDD

### ISSUE THREAD

**Issue by ipdork** [Athena-OS/athena#107]
### Athena OS version

rolling

### Which environment or technology are you using?

- [X] Baremetal
- [ ] VirtualBox Virtual Machine
- [ ] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Repro steps

![Screenshot_2024-01-23_21-19-23](https://github.com/Athena-OS/athena-iso/assets/149003005/a93d5971-226d-445d-859a-11eb2928a626)
![Screenshot_2024-01-23_21-19-11](https://github.com/Athena-OS/athena-iso/assets/149003005/533f0564-b09d-41bf-aec8-cc968779a0a3)

### Expected behavior

reboot to full athena os

### Actual behavior

installation fails

**Comment by D3vil0p3r** [comment]
When did you download the ISO?

**Comment by D3vil0p3r** [comment]
@ipdork use https://github.com/Athena-OS/athena/releases/tag/v23.11

Can I close the issue?
