### ISSUE TITLE
when i boot iso from vm it goes to the menu, i choose the opensource/ existing os one and it counts down to 15 then nothing

### ISSUE THREAD

**Issue by richoffpints** [Athena-OS/athena#108]
am i missing something, when i boot iso from vm it goes to the menu, i choose the opensource/ existing os one and it counts down to 15 then nothing

**Comment by D3vil0p3r** [comment]
Which ISO did you download?

**Comment by richoffpints** [comment]
iv tryed many iso from here, source forge, over many months. is there VM settings im missing? i cant find anyone eles with same issue

**Comment by D3vil0p3r** [comment]
Currently we are migrating Athena OS from Arch to Nix, so we think to deploy directly the new Athena based on Nix, at least in a pre-release version.

**Comment by richoffpints** [comment]
so what were do i get the new version

**Comment by D3vil0p3r** [comment]
Just wait

**Comment by D3vil0p3r** [comment]
> so what were do i get the new version

Did you try: https://github.com/Athena-OS/athena/releases/tag/v23.11 ?
