### ISSUE TITLE
[BUG]: Failed to start Virtual Console Setup

### ISSUE THREAD

**Issue by d-obfuscation** [Athena-OS/athena#109]
### Athena OS version

Not sure (Downloaded ISO on 28/01/2024 at around 5pm GMT)

### Which environment or technology are you using?

- [X] Baremetal
- [ ] VirtualBox Virtual Machine
- [X] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Kernel version

unsure, default linux kernel

### Involved software

N/A

### Repro steps

1. Boot from flash drive into Athena OS
2. Click Online Install
3. Once installed, reboot

### Expected behavior

After step 3, expectation is to boot into the login screen and then be able to use Athena OS

### Actual behavior

After installing AthenaOS, upon rebooting I am met with a black saying "[FAILED] Failed to start Virtual Console Setup" on the very top left.
(Note: I have both tested this in a Virtual machine (VMware) and baremetal on my actual PC, results were the same)

**Comment by D3vil0p3r** [comment]
Try to use: https://github.com/Athena-OS/athena/releases/tag/v23.11
