### ISSUE TITLE
[BUG]: After installation, only one cursor is displayed when launched

### ISSUE THREAD

**Issue by Athrun-Judah** [Athena-OS/athena#110]
### Athena OS version

Athena OS "Polias"

### Which environment or technology are you using?

- [ ] Baremetal
- [X] VirtualBox Virtual Machine
- [ ] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Repro steps

1.Step by step online installation.
2.Hyprland was selected for the desktop and GDM is the initiator.The kernel is linux-zen.Others are the default.
3.Reboot after completing the installation.

![2024-01-31_21-59](https://github.com/Athena-OS/athena-nix/assets/66123941/7f8713c2-02af-4d9e-b91f-83cf81818f4a)
![2024-01-31_21-59_1](https://github.com/Athena-OS/athena-nix/assets/66123941/cfadf409-e330-4dce-ac29-a030ca8f1c9a)
![2024-01-31_22-00](https://github.com/Athena-OS/athena-nix/assets/66123941/0a820198-c951-4011-99b6-2e2188dccd74)

### Expected behavior

Normal access to the system 

### Actual behavior

Only one cursor is displayed when launched.

**Comment by D3vil0p3r** [comment]
We are migrating from Arch to Nix. In few days all those issues will be not applicable. Follow us on Discord to get the latest updates.

**Comment by D3vil0p3r** [comment]
@Athrun-Judah use the pre-release ISO please: https://github.com/Athena-OS/athena/releases/tag/v23.11

**Comment by Athrun-Judah** [comment]
Thanks,  I'll try it.
