### ISSUE TITLE
[BUG]: Instalator is not going to start (message: INIT NOT FOUND)

### ISSUE THREAD

**Issue by DDrozdzz-1066** [Athena-OS/athena#113]
### Athena OS version

Athena OS "Nyx"

### Which environment or technology are you using?

- [x] Baremetal
- [ ] VirtualBox Virtual Machine
- [ ] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Repro steps

This happens when I run the installer from ventoy, and choosing first option from boot screen

### Expected behavior

Properly working instaler

### Actual behavior

When trying to run the installer by selecting the first option from the boot screen, the system returns the message "INIT NOT FOUND" in red after the earlier (first) message "[0.151075] x86/cpu: SGX disabled by BIOS".

**Comment by D3vil0p3r** [comment]
Use another software instead of Ventoy. Try Rufus or Balena Etcher

**Comment by DDrozdzz-1066** [comment]
> Use another software instead of Ventoy. Try Rufus or Balena Etcher

Changing the software worked. After this procedure, the system boot went successfully.

**Comment by D3vil0p3r** [comment]
> > Use another software instead of Ventoy. Try Rufus or Balena Etcher
> 
> Changing the software worked. After this procedure, the system boot went successfully.

Can I close the issue?
