### ISSUE TITLE
[BUG]: Error when rebuilding system using configuration file during isntalation athena over nix os

### ISSUE THREAD

**Issue by DDrozdzz-1066** [Athena-OS/athena#116]
### Athena OS version

Athena OS "Nyx"

### Which environment or technology are you using?

- [X] Baremetal
- [ ] VirtualBox Virtual Machine
- [ ] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Repro steps

This happens when I try to rebuild my system using the edited configuration file after the previous steps in the instruction from official website

### Expected behavior

Properly working Athena OS "Nyx" system.

### Actual behavior

I got an error in the console when I try to rebuild my system: 
"systemd[1]: home-manager-_(username)_.service: Failed with result 'exit-code'." 
"systemd[1]: Failed to start Home Manager environment for _(username)_."

### Diagnostic logs

![Zrzut ekranu z 2024-02-09 16-05-02](https://github.com/Athena-OS/athena-nix/assets/71146814/a506d91f-f7e4-4eb5-9337-017d967fade7)

**Comment by shard77** [comment]
Hello, this is a bug due to Home Manager, which is what we use to manage user dotfiles.
As written in the error, you can simply remove the file that is in conflict in the new one and then rebuild.

**Comment by DDrozdzz-1066** [comment]
> Hello, this is a bug due to Home Manager, which is what we use to manage user dotfiles. As written in the error, you can simply remove the file that is in conflict in the new one and then rebuild.

Removing these files worked. I had to remove two files: "profiles.ini" in "/.mozilla/firefox/" directories in my home directory on first try running after running "sudo nixos-rebuild switch" command and "config.fish" on second try after running same command, and the file was locates /.config/fish/ directories in my home directory either.

**Comment by shard77** [comment]
> > Hello, this is a bug due to Home Manager, which is what we use to manage user dotfiles. As written in the error, you can simply remove the file that is in conflict in the new one and then rebuild.
> 
> Removing these files worked. I had to remove two files: "profiles.ini" in "/.mozilla/firefox/" directories in my home directory on first try running after running "sudo nixos-rebuild switch" command and "config.fish" on second try after running same command, and the file was locates /.config/fish/ directories in my home directory either. After theese steps rebuilding of system is succesfully completed

Alright, @D3vil0p3r , can you close this?

**Comment by D3vil0p3r** [comment]
@DDrozdzz-1066 can you try again if you get the same issue now?
