### ISSUE TITLE
[QUESTION]: Will Athena-OS based on ArchLinux continue to run?

### ISSUE THREAD

**Issue by JoJenH** [Athena-OS/athena#124]
## Question
I noticed that there are two git repositories and both are updated recently.
![image](https://github.com/Athena-OS/athena/assets/45531537/5ea55c1c-75f3-4fe0-a4d0-fd8332287217)
It looks like the first one is Arch-based.
Love Arch, Athena and penetration testing and don't want them to break up.  I can tolerate AthenaOS affair with NixOS, but please don't abandon Arch, please?

**Comment by D3vil0p3r** [comment]
@JoJenH currently Athena OS will support both Arch and NixOS environment.
