### ISSUE TITLE
[QUESTION]:Athena Arch not installing

### ISSUE THREAD

**Issue by Azguard-Cybernetics** [Athena-OS/athena#125]
## Question
hi there iv been trying to install athena os (Arch) but it keeps failing  with a few errors such as athena os-release file not found no such file or directory and (error: blackarch: signature from 'Levon 'noptrix' Kayan (BlackArch Developer)) is there a solution to these errors?

**Comment by D3vil0p3r** [comment]
Hello. athena-os-release error is not a real error. it is not blocking. About BlackArch key, you are using an old ISO. Download the new beta one: https://athenaos.org/

**Comment by Azguard-Cybernetics** [comment]
> Hello. athena-os-release error is not a real error. it is not blocking. About BlackArch key, you are using an old ISO. Download the new beta one: https://athenaos.org/

Okay thanks i will try the new one

**Comment by MishchenkoA** [comment]
Actually there is an error in aegis code (https://github.com/Athena-OS/aegis/blob/main/aegis-arch/src/functions/base.rs line 227) - the source file should be `/usr/lib/os-release-athena `, not `/mnt/usr/lib/os-release-athena`
![image](https://github.com/Athena-OS/athena/assets/48956115/44569402-3724-485d-81ef-9df9badb1888)

**Comment by D3vil0p3r** [comment]
@MishchenkoA in theory it is not an error. In practice `athena-config` should install `os-release-athena` in the mounted partition, then, this file is copied to `os-release`.

**Comment by MishchenkoA** [comment]
@D3vil0p3r no man, on practice fighting with installer right now - it is broken at all)  Have you tried use it after updates? After antenna-config will install the `os-release` on mounted partition - it will not create `os-release-athena`, only `os-release`. The same situation with a lot of other files. Sometimes you need copy all the folder from parent to mounted partition to bypass error (like `/usr/share/applications` to `/mnt/usr/......`), sometimes installer is trying to copy the files which were not created and so on. Please try install it on clear VM, you will see. For regular user it is not impossible to install and test it. TBH - the distro is great but installer has a lot of bugs ATM, at least for arch. And I do not understand logic when you choose cop

**Comment by D3vil0p3r** [comment]
@MishchenkoA about [athena-config](https://github.com/Athena-OS/athena/blob/main/packages/os-specific/athena-config/PKGBUILD) look its PKGBUILD and you see:
```bash
cp -rf "${srcdir}/usr/lib/os-release-athena" "${pkgdir}/usr/lib/"
```
It means that it installs `os-release-athena` only. It is installed in `/mnt` because all packages are installed in `/mnt` by Aegis. The file `os-release` is just created by Aegis installer as copy of the first file..

About the errors, just ignore the `exit code 0` errors, because `code 0` means `successful`. Only `exit code 1` are real errors. If your installation interrupts because an error, please share your logs with me by the links produced by:
```
install-logs
config-logs
```
These commands are available only if you downloaded the ISO today.

**Comment by MishchenkoA** [comment]
@D3vil0p3r can you gimme straight link to fresh iso? maybe I am fighting with shadows))

**Comment by MishchenkoA** [comment]
![image](https://github.com/Athena-OS/athena/assets/48956115/f98cb363-7c68-4c50-a643-01073f87eb3c)
Tis one?

**Comment by D3vil0p3r** [comment]
> @D3vil0p3r can you gimme straight link to fresh iso? maybe I am fighting with shadows))

https://github.com/Athena-OS/athena/releases/tag/v23.11

Until this morning I needed to upload the new ISO due to a dropped package that caused install failing.

**Comment by D3vil0p3r** [comment]
> ![image](https://github.com/Athena-OS/athena/assets/48956115/f98cb363-7c68-4c50-a643-01073f87eb3c)
> Tis one?
> 

Yes

**Comment by MishchenkoA** [comment]
@D3vil0p3r looks like all works, thanks for assistance, will try distro on practice.

**Comment by Azguard-Cybernetics** [comment]
> > @D3vil0p3r can you gimme straight link to fresh iso? maybe I am fighting with shadows))
> 
> https://github.com/Athena-OS/athena/releases/tag/v23.11
> 
> Until this morning I needed to upload the new ISO due to a dropped package that caused install failing.

i figured that out not to long ago but on every install this far i the red team role does not install
