### ISSUE TITLE
[QUESTION]:

### ISSUE THREAD

**Issue by Azguard-Cybernetics** [Athena-OS/athena#128]
![Screenshot from 2024-05-30 16-03-00](https://github.com/Athena-OS/athena/assets/148313890/a6a8dd8a-9f8f-4b3e-9415-7b393b15124e)
## i cant seem to install red team when selecting the role is it due to an update because i updated the system?

**Comment by D3vil0p3r** [comment]
https://archlinux.org/packages/extra/any/python-pyppeteer/ has been dropped from Arch repository.

**Comment by D3vil0p3r** [comment]
I added the missing deps. Run:
```
sudo pacman -Syyu
```
and try again to run the Red Team role.

**Comment by Azguard-Cybernetics** [comment]
> I added the missing deps. Run:
> 
> ```
> sudo pacman -Syyu
> ```
> 
> and try again to run the Red Team role.

it works thanks
