### ISSUE TITLE
how to install in ?[QUESTION]:

### ISSUE THREAD

**Issue by mojidoji** [Athena-OS/athena#129]
## Question
i downloaded but i can't really install it, there is no option for installing it offilne

i think the installer is gone now, so how do install it?

**Comment by D3vil0p3r** [comment]
Did you download Athena Nyx from GitHub? Currently offline install is not available

**Comment by mojidoji** [comment]
> Did you download Athena Nyx from GitHub? Currently offline install is not available

no the previous one i downloaded

**Comment by D3vil0p3r** [comment]
The previous one is broken.

**Comment by mojidoji** [comment]
> The previous one is broken.

aha so which version should i install and is there any htb in it?

**Comment by D3vil0p3r** [comment]
The prerelease. Look on https://athenaos.org
