### ISSUE TITLE
[QUESTION]:Installation failed

### ISSUE THREAD

**Issue by DmcforSpc** [Athena-OS/athena#131]
## Question
Problem installing Athena OS "Nyx", installation failed, log https://termbin.com/qk2q

**Comment by D3vil0p3r** [comment]
What are the resources of your host? Vm or baremetal?

**Comment by DmcforSpc** [comment]
> 您的主机有哪些资源？VM还是裸机？

I use vmware for installation

**Comment by D3vil0p3r** [comment]
> > 您的主机有哪些资源？VM还是裸机？
> 
> I use vmware for installation

How did you configure the virtual machine?

**Comment by DmcforSpc** [comment]
> > > 您的主机有哪些资源？VM还是裸机？
> > 
> > 
> > I use vmware for installation
> 
> How did you configure the virtual machine?

![image](https://github.com/Athena-OS/athena/assets/102737018/a86fdb56-90e8-469e-a5d9-c73f25a6faee)

**Comment by SystemXzz** [comment]
I also encountered the same problem

**Comment by D3vil0p3r** [comment]
Can you also provide which choices did you do during the install? (e.g., theme, DE, Display Manager)

**Comment by DmcforSpc** [comment]
> Can you also provide which choices did you do during the install? (e.g., theme, DE, Display Manager)

Here is the basic configuration for details
┃   ┌─────────────────────────────┐
┃   │                             │
┃   │  Summary, is this correct?  │
┃   │                             │
┃   │  console keymap: 3l         │
┃   │  GUI keymap: af             │
┃   │  timezone: Africa/Abidjan   │
┃   │  locale: aa_DJ.UTF-8 UTF-8  │
┃   │  username: athena           │
┃   │  password: athena           │
┃   │  root-password: athena      │
┃   │  hostname: xad              │
┃   │  disk: /dev/sda             │
┃   │  shell: bash                │
┃   │  desktop: gnome             │
┃   │  theme: akame               │
┃   │  display manager: gdm       │
┃   │  browser: firefox           │
┃   │  terminal: alacritty        │
┃   │  ipv6: false                │
┃   │  enable zramd: false        │
┃   │  enable flatpak: false      │
┃   │  efi: false                 │
┃   │                             │
┃   └─────────────────────────────┘

 ┌───────────────────────────────────────────────────────────────────────┐
 │                                                                       │
 │  Please enter the number of cores assigned to the installer (0: all)  │
 │                                                                       │
 └───────────────────────────────────────────────────────────────────────┘
I enter 0 here
 
  ┌─────────────────────────────────────────────────────────────────────┐
 │                                                                     │
 │  Please enter the number of maximum jobs assigned to the installer  │
 │                                                                     │
 └─────────────────────────────────────────────────────────────────────┘
I enter 0 here (I don't quite understand what to input here)

**Comment by DmcforSpc** [comment]
> > Can you also provide which choices did you do during the install? (e.g., theme, DE, Display Manager)
> 
> Here is the basic configuration for details ┃ ┌─────────────────────────────┐ ┃ │ │ ┃ │ Summary, is this correct? │ ┃ │ │ ┃ │ console keymap: 3l │ ┃ │ GUI keymap: af │ ┃ │ timezone: Africa/Abidjan │ ┃ │ locale: aa_DJ.UTF-8 UTF-8 │ ┃ │ username: athena │ ┃ │ password: athena │ ┃ │ root-password: athena │ ┃ │ hostname: xad │ ┃ │ disk: /dev/sda │ ┃ │ shell: bash │ ┃ │ desktop: gnome │ ┃ │ theme: akame │ ┃ │ display manager: gdm │ ┃ │ browser: firefox │ ┃ │ terminal: alacritty │ ┃ │ ipv6: false │ ┃ │ enable zramd: false │ ┃ │ enable flatpak: false │ ┃ │ efi: false │ ┃ │ │ ┃ └─────────────────────────────┘
> 
> ┌───────────────────────────────────────────────────────────────────────┐ │ │ │ Please enter the number of cores assigned to the installer (0: all) │ │ │ └───────────────────────────────────────────────────────────────────────┘ I enter 0 here
> 
> ┌─────────────────────────────────────────────────────────────────────┐ │ │ │ Please enter the number of maximum jobs assigned to the installer │ │ │ └─────────────────────────────────────────────────────────────────────┘ I enter 0 here (I don't quite understand what to input here)

Here is the error log for this configuration installation https://termbin.com/6xts

**Comment by D3vil0p3r** [comment]
I think that maybe, if your government restricts Internet, you should try a VPN to install Athena

**Comment by DmcforSpc** [comment]
> I think that maybe, if your government restricts Internet, you should try a VPN to install Athena

I used VPN, maybe it didn't work. I'm trying to try, sorry to bother you

**Comment by shamoldev** [comment]
I have a problem in installation, I was installing via Athena Welcome. Can who help me?

**Comment by shamoldev** [comment]
┃
┃   ┌─────────────────────────────┐
┃   │                             │
┃   │  Summary, is this correct?  │
┃   │                             │
┃   │  console keymap: en         │
┃   │  GUI keymap: us             │
┃   │  timezone: Asia/Tashkent    │
┃   │  locale: en_US.UTF-8 UTF-8  │
┃   │  username: sr               │
┃   │  password: 1945             │
┃   │  root-password: 1945        │
┃   │  hostname: redops           │
┃   │  disk: /dev/nvme0n1         │
┃   │  shell: none                │
┃   │  desktop: hyprland             │
┃   │  theme: none                │
┃   │  display manager: sddm      │
┃   │  browser: firefox           │
┃   │  terminal: kitty            │
┃   │  ipv6: false                │
┃   │  enable zramd: false        │
┃   │  enable flatpak: false      │
┃   │  efi: true                  │
┃   │                             │
┃   └─────────────────────────────┘
┃
┃
┃            Yes        No

**Comment by D3vil0p3r** [comment]
Edit your comment and delete password lines please.

**Comment by shamoldev** [comment]
Okay

Dush, 5-avg, 2024, 20:12 D3vil0p3r ***@***.***>:

**Comment by shamoldev** [comment]
what's link?
