### ISSUE TITLE
[QUESTION]:Installation error

### ISSUE THREAD

**Issue by SystemXzz** [Athena-OS/athena#132]
## Question
An error occurred during installation using the Aegis Installer TUI. Log file: [https://termbin.com/d7b3](https://termbin.com/d7b3)
virtual machine configuration is the same as the official documentation of vmware installation of athena os
This is the option I made during installation：
![200097f5d4e76f02e327411a594b719](https://github.com/Athena-OS/athena/assets/90515934/2699840c-6ca7-406d-adf6-794f71b75c8d)

**Comment by SystemXzz** [comment]
Hello, developer of Athena OS, I solved the above problem by using VPN, but now I have a new problem. TUI shows that I have completed the installation, but I cannot enter the system after deleting the CD launcher and restarting. Since the log is not automatically sent after the installation is completed, I use paste.sh to transfer the log. This is my installation log:[aegis.log](https://paste.sh/PYRgFBj7#UEsX8-BuPhm6LU6cHZeZyCrO) @D3vil0p3r

**Comment by D3vil0p3r** [comment]
```
[ INFO ] 05:18:31 /nix/store/wmjka9s5mr4xg7vqs6vidds72c0f1mfm-grub-2.12/sbin/grub-install: warning: this GPT partition label contains no BIOS Boot Partition; embedding won't be possible.
```
Are you using UEFI or GRUB Legacy?

**Comment by eogod** [comment]
I have the same problem. I'm on baremetal and use UEFI

**Comment by D3vil0p3r** [comment]
Sorry guys. It was my error in Athena Nix configuration. Now it should work again. Please retry.

**Comment by SystemXzz** [comment]
> Sorry guys. It was my error in Athena Nix configuration. Now it should work again. Please retry.

After trying, I encountered a new error. My configuration is the same as before. My aegis.log: [https://termbin.com/xc7k](https://termbin.com/xc7k)

**Comment by D3vil0p3r** [comment]
> > Sorry guys. It was my error in Athena Nix configuration. Now it should work again. Please retry.
> 
> After trying, I encountered a new error. My configuration is the same as before. My aegis.log: https://termbin.com/xc7k

Now it should work. Please retry.
