### ISSUE TITLE
[BUG]: Circular dependency problem while installing a package group from cyber-toolkit OSINT..

### ISSUE THREAD

**Issue by Kalidude69** [Athena-OS/athena#134]
### Athena OS version

sorry im on cachy-os :D

### Which environment or technology are you using?

- [X] Baremetal
- [ ] VirtualBox Virtual Machine
- [ ] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Kernel version

6.10.0-1-cachyos-bore

### Involved software

python-tiffile 2024.7.2-1 and python-scikit-image these are the two packages which simultaneously require each other while installing the OSINT group packages this dependency error comes up....problem is that python-tiffffile isnt available in the arch repos but its available on the aur but scikit is availabe on the repos but they wont work bcoz they need each other while installing .....

### Repro steps

1 > Try to install from aur wont work due to dependency issues
2 > Cannot find a way to build them independently
3 >  I know about pip packages but they wont obviously mix up with pacman

### Expected behavior

Was expecting the osint package group to work ... it didn't so raised a issue about it :D

### Actual behavior

**Logs are provided below of the stuff happening thank you for your concern**

### Diagnostic logs

``````
Enter a number (default=1):
:: The following package cannot be upgraded due to unresolvable dependencies:
      athena-osint

:: Do you want to skip the above package for this upgrade? [y/N]
:: unable to satisfy dependency 'python-tifffile>=2022.8.12' required by python-scikit-image
:: unable to satisfy dependency 'python-scikit-image' required by social-mapper
:: unable to satisfy dependency 'social-mapper' required by athena-osint
pacman err (exit code 1): warning: cannot resolve "python-tifffile>=2022.8.12", a dependency of "python-scikit-image"
pacman err (exit code 1): warning: cannot resolve "python-scikit-image", a dependency of "social-mapper"
pacman err (exit code 1): warning: cannot resolve "social-mapper", a dependency of "athena-osint"
pacman err (exit code 1): error: failed to prepare transaction (could not satisfy dependencies)
The package manager failed with exit code: 1
All done. Your role has been set!
Press Enter to continue

**Comment by D3vil0p3r** [comment]
I just tested athena-osint and it works well... Which repository are you using?

**Comment by Kalidude69** [comment]
Which repository ? there is an athena repo and a blackarch repo i added ...all other tools work fine other than osint...


> I just tested athena-osint and it works well... Which repository are you using?

**Comment by Kalidude69** [comment]
athena only has one repo probably ??

**Comment by Kalidude69** [comment]
i fixed it .... just ran `#pacman -Sdd (specific tools)`now it works sorry for raising this dumb issue

**Comment by D3vil0p3r** [comment]
You are welcome. Btw Athena does not use BlackArch repo. It uses its own repo for pentesting.

**Comment by Kalidude69** [comment]
> You are welcome. Btw Athena does not use BlackArch repo. It uses its own repo for pentesting.

yes sir I am aware about it ... i just added another one for bychance if I dont get any package or the repo speeds are slow for that reason i have kept it .....

**Comment by Kalidude69** [comment]
would be really helpful if you could guide me as a student on what to do and how to start with cybersecurity and programming in general .... :).... btw great project it has inspired me a lot @D3vil0p3r

**Comment by D3vil0p3r** [comment]
Join our Discord server and try to ask there
