### ISSUE TITLE
[QUESTION]:nixos vs arch experience 

### ISSUE THREAD

**Issue by abhinavpatel0** [Athena-OS/athena#135]
## Question
My question is why it is written in docs that the minimum requirements for arch version is 2gb but for nix os is it's double 4gb,

Will there be performance issues if I use nixos instead of arch in my i3 11th gen 4gb ram , 256gb SSD laptop?

Are there more ram usage in nix version compared to arch ?

Please help me out and share your experience

**Comment by D3vil0p3r** [comment]
We observed that if you don't use that amount of Ram in Nix version, at least in VM, the install freezes. But not sure in baremetal.

**Comment by skssjsjjssjnd** [comment]
I'm a bare metal installation

**Comment by D3vil0p3r** [comment]
> I'm a bare metal installation

you can try to test then by 4 GB and inform me if you get issues, if the install freezes.

**Comment by abhinavpatel0** [comment]
> We observed that if you don't use that amount of Ram in Nix version, at least in VM, the install freezes. But not sure in baremetal.



> We observed that if you don't use that amount of Ram in Nix version, at least in VM, the install freezes. But not sure in baremetal.

How much ram the nix os version will use after installation?

**Comment by D3vil0p3r** [comment]
I use 8 GB. You can try also 4 GB even if I never tested it.
