### ISSUE TITLE
[QUESTION]:a question

### ISSUE THREAD

**Issue by skssjsjjssjnd** [Athena-OS/athena#136]

**Comment by skssjsjjssjnd** [comment]
and this

**Comment by skssjsjjssjnd** [comment]
install also failed

**Comment by skssjsjjssjnd** [comment]
why is that

**Comment by D3vil0p3r** [comment]
Dont use Ventoy

**Comment by skssjsjjssjnd** [comment]
understand

**Comment by skssjsjjssjnd** [comment]
lt's been all afternoon

**Comment by skssjsjjssjnd** [comment]
balena etcher is that ok

**Comment by skssjsjjssjnd** [comment]
I feel that your system has finished hanging kali long ago

**Comment by skssjsjjssjnd** [comment]
Why can't I install it? I'll give you the error. You can analyze it

**Comment by skssjsjjssjnd** [comment]
Still not. He said he detected a failure to synchronize Intel's database

**Comment by D3vil0p3r** [comment]
Come on Discord to discuss by a chat
