### ISSUE TITLE
[QUESTION]:Arch Version - Installastion Failed

### ISSUE THREAD

**Issue by Beegchonk** [Athena-OS/athena#139]
## Question

Hello - I was booting up and installing the recent version of Athena OS onto my Virtual box and When I got to the actual installation process of the VM - It failed towards the end. I have the termbin links down below.

Install logs: https://[termbin.com/fg0zg] (https://termbin.com/fg0zg)

Config Logs: https://[termbin.com/fuft] (https://termbin.com/fuft)

Was there something I've set up incorrectly?

**Comment by D3vil0p3r** [comment]
The problem was `marktext` package dropped from Chaotic AUR repository. Now the installation should work. Try please and let me know.

**Comment by D3vil0p3r** [comment]
I assume it has been solved. Closing.
