### ISSUE TITLE
how can i dualboot with windows 11?

### ISSUE THREAD

**Issue by lucasterly** [Athena-OS/athena#14]

**Comment by zeeshan1991k** [comment]
i also could not dual boot athena os with windows 11. Wasted whole say doing that, Also flameshot does not work on gnome in athena os,

**Comment by D3vil0per** [comment]
> i also could not dual boot athena os with windows 11. Wasted whole say doing that, Also flameshot does not work on gnome in athena os,

Guys please, details the steps you are taking for that and the errors you get. If you would like to test together, reach us on Discord. Link on the README.
