### ISSUE TITLE
[QUESTION]:HTB API KEY

### ISSUE THREAD

**Issue by dottorGREG** [Athena-OS/athena#144]
## Question
I tried to set my own htb key but When I insert the Key it locks holding the terminal open and does not go forward

**Comment by D3vil0p3r** [comment]
What is the specific output u get when you run `htb-toolkit -k reset` and paste your app key in Password field?

**Comment by dottorGREG** [comment]
> What is the specific output u get when you run `htb-toolkit -k reset` and paste your app key in Password field?



> What is the specific output u get when you run `htb-toolkit -k reset` and paste your app key in Password field?

None. It does not find any Key set, it gives me the prompt to paste the new Key generated Then it stays there

**Comment by D3vil0p3r** [comment]
Can you record a video?

**Comment by dottorGREG** [comment]
> Can you record a video?

No ok it seems to have resolved itself
