### ISSUE TITLE
[BUG]: unable to satisfy dependency 'python-future'

### ISSUE THREAD

**Issue by ex3ploit3r** [Athena-OS/athena#153]
### Athena OS version

v23.11 

### Which environment or technology are you using?

- [X] Baremetal
- [ ] VirtualBox Virtual Machine
- [ ] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Kernel version

6.6.67-1-lts

### Repro steps

 sudo pacman -S athena-student

#othe athena-packages also not working (web pentester ,red teamer)

### Expected behavior

to install athena-student  

### Actual behavior

[👾]/home/sha4 $ sudo pacman -S athena-student
warning: athena-student-1.0.0-3 is up to date -- reinstalling
resolving dependencies...
warning: cannot resolve "python-future", a dependency of "python-python-whois"
warning: cannot resolve "python-python-whois", a dependency of "spiderfoot"
warning: cannot resolve "python-future", a dependency of "spiderfoot"
warning: cannot resolve "spiderfoot", a dependency of "athena-student"
:: There are 10 providers available for java-runtime>=9:
:: Repository extra
   1) jdk-openjdk  2) jdk11-openjdk  3) jdk17-openjdk  4) jdk21-openjdk
   5) jre-openjdk  6) jre11-openjdk  7) jre17-openjdk  8) jre21-openjdk
:: Repository chaotic-aur
   9) jdk  10) jre

Enter a number (default=1): 
warning: cannot resolve "python-future", a dependency of "wfuzz"
warning: cannot resolve "wfuzz", a dependency of "athena-student"
:: The following package cannot be upgraded due to unresolvable dependencies:
      athena-student

:: Do you want to skip the above package for this upgrade? [y/N] N
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'python-future' required by python-python-whois
:: unable to satisfy dependency 'python-python-whois' required by spiderfoot
:: unable to satisfy dependency 'python-future' required by spiderfoot
:: unable to satisfy dependency 'spiderfoot' required by athena-student
:: unable to satisfy dependency 'python-future' required by wfuzz
:: unable to satisfy dependency 'wfuzz' required by athena-student
┌──[HQ🚀🌐192.168.222.20🔥sha4]

### Diagnostic logs

python-future package

**Comment by D3vil0p3r** [comment]
Run `sudo pacman -Syy` and try again.

**Comment by ex3ploit3r** [comment]
> Run `sudo pacman -Syy` and try again.

   5) jre-openjdk  6) jre11-openjdk  7) jre17-openjdk  8) jre21-openjdk
:: Repository chaotic-aur
   9) jdk  10) jre

Enter a number (default=1): 
looking for conflicting packages...
warning: dependency cycle detected:
warning: python-soupsieve will be installed before its python-beautifulsoup4 dependency
warning: dependency cycle detected:
warning: python-incremental will be installed before its python-twisted dependency

somehow now working
