### ISSUE TITLE
[BUG]: fail to update

### ISSUE THREAD

**Issue by Mohadib2** [Athena-OS/athena#91]
### Athena OS version

athena os v23.06.03

### Which environment or technology are you using?

- [x] Baremetal
- [ ] VirtualBox Virtual Machine
- [X] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Kernel version

6.6.2-zen1-1-zen

### Repro steps

when upgrading i have an error says
failed retrieving file 'athena-repository.db' from athena-os.github.io : The requested URL returned error: 404
hapens with multiple athena installations in bare metal and virtual enviroments

### Expected behavior

update

### Actual behavior

error

**Comment by D3vil0p3r** [comment]
https://github.com/Athena-OS/athena-repository/issues/6

**Comment by D3vil0p3r** [comment]
Old ISO. I close the issue.
