### ISSUE TITLE
[QUESTION]:

### ISSUE THREAD

**Issue by Hirukshapro** [Athena-OS/athena#92]
## OS Install Error 

* I keep on getting this error while try to install Athena OS

![image](https://github.com/Athena-OS/athena-iso/assets/96366852/b375706d-3676-4dd1-92f9-67e6388a69f1)

**Comment by D3vil0p3r** [comment]
Share the log file please. You can find it at `/tmp/aegis.log`.

**Comment by Hirukshapro** [comment]
![image](https://github.com/Athena-OS/athena-iso/assets/96366852/892bc63f-e2e6-4f64-829c-9704d146cf9d)

**Comment by D3vil0p3r** [comment]
You are using an old ISO. Download the latest one

**Comment by D3vil0p3r** [comment]
@Hirukshapro did the latest ISO work for you?
