### ISSUE TITLE
[BUG]: things stoped working after update

### ISSUE THREAD

**Issue by Mohadib2** [Athena-OS/athena#94]
### Athena OS version

athena os v23.06.03

### Which environment or technology are you using?

- [ ] Baremetal
- [ ] VirtualBox Virtual Machine
- [X] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Repro steps

update

### Expected behavior

everything to work

### Actual behavior

after the update some things stoped working 
in the athena wellcome the buttons upgrade, set rule, release info no longer work
some extentions not working to 
i think its becuse the installation of the gnome-shell-perfomance 
when trying to update i cant procees until i chose to remove the gnome-shell because its in conflict with gnome-shell-performance
am i doing something not as i suppose to do.
thank you

**Comment by D3vil0p3r** [comment]
Did the solution work?

**Comment by D3vil0p3r** [comment]
In theory the rolling ISO has this purpose

**Comment by D3vil0p3r** [comment]
@Mohadib2 did you solve the issue?

**Comment by D3vil0p3r** [comment]
No. Also Athena Arch is supported.
