### ISSUE TITLE
Athena is installar not run offline install option not show what problem [QUESTION]:

### ISSUE THREAD

**Issue by Sumangal44** [Athena-OS/athena#97]
Athena is installar not run offline install option not show what problem [QUESTION]:

**Comment by D3vil0p3r** [comment]
Athena currently has no offline installer.

**Comment by E1Gnt** [comment]
> Athena currently has no offline installer.

When will the new offline installer be available? There are some issues with the 2023.06.23 version.

**Comment by D3vil0p3r** [comment]
> > Athena currently has no offline installer.
> 
> When will the new offline installer be available? There are some issues with the 2023.06.23 version.

That version is too old. Currently we are testing Athena Nix for Nix Users and there is a poll/survey on Discord server where users will decide the next steps of Athena project.
