### ISSUE TITLE
[BUG]: After the system woke up form suspend I have a blank black screen.

### ISSUE THREAD

**Issue by DDrozdzz-1066** [Athena-OS/athena#98]
### Athena OS version

Athena OS Rolling release

### Which environment or technology are you using?

- [X] Baremetal
- [ ] VirtualBox Virtual Machine
- [ ] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Kernel version

6.6.8-arch1-1

### Repro steps

1. Suspend system
2. Wake up the system

### Expected behavior

Login manager available and ready to use

### Actual behavior

Blank black screen

**Comment by D3vil0p3r** [comment]
No enough information (desktop environment installed, display manager, no screenshot). Please give details.

**Comment by D3vil0p3r** [comment]
Are you still experiencing this issue @DDrozdzz-1066 ?
